---
- name: this playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Playbook execution Begin."

  roles:
    - datadisk
    - system_profile
    - users
    - webserver

  post_tasks:
    - debug: 
        msg: "Playbook execution completed."
